site_name: FreelanceJoy
nav:
  - Home: 'index.md'
  - Studies:
    - Case Study: 'caseStudy.md'
    - Existing Solutions: 'existingSolutions.md'
  - Use Cases: 'useCases.md'
  - Business Canvas: 'businessCanvas.md'
  - Architecture: architecture.md
  - Bibliography: 'bibliography.md'
